name: YouTube Shorts Live

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          # Bu qator rasm nomini avtomatik aniqlaydi (jpg yoki png bo'lsa ham)
          FILE=$(ls image.* | head -n 1)
          ffmpeg -re -loop 1 -i "$FILE" -f lavfi -i anullsrc -c:v libx264 -preset veryfast -tune stillimage -pix_fmt yuv420p -g 60 -b:v 3000k -c:a aac -ar 44100 -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
